# Section sign as leader.
unbind C-b
set-option -g prefix "0xa7"
bind-key "0xa7" send-prefix

set -g escape-time 0
set -g focus-events on
set -g xterm-keys on

set -g base-index 1
set -g pane-base-index 1

set -g default-terminal "tmux-256color"
set -g status-position bottom
set -g status-justify centre
set -g status-interval 5
set -g status-left-length 180
set -g status-right-length 150

set -g @system_theme_script "$HOME/.config/tmux/apply-system-theme.sh"
set -g @plugin 'tmux-plugins/tmux-battery'

setw -g monitor-activity on

set -g pane-border-status top
bind T command-prompt -p "pane name" -I "#{pane_title}" "select-pane -T '%%'"

set -g mouse on

setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

set -g history-limit 50000

bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

bind-key -n M-h resize-pane -L 3
bind-key -n M-j resize-pane -D 3
bind-key -n M-k resize-pane -U 3
bind-key -n M-l resize-pane -R 3

is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"

bind-key -n C-h if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n C-j if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n C-k if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n C-l if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

set-environment -g PATH "/opt/homebrew/bin:/usr/local/bin:/bin:/usr/bin:/usr/sbin:/sbin"
run '~/.tmux/plugins/tpm/tpm'
run-shell -b '~/.config/tmux/apply-system-theme.sh --force'
