name: dev
root: "<%= ENV['TS_ROOT'] || '~/' %>"

windows:
  - editor:
      layout: 0964,210x50,0,0[210x35,0,0,0,210x14,0,36,1]
      panes:
        - editor:
            - nvim .
        - term:
  - git:
      panes:
        - git:
            - git rev-parse --is-inside-work-tree 2>/dev/null && lazygit
  - ai:
      panes:
        - copilot:
            - copilot
